citycar/Controllers/ProprietairesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using citycar.Data;
using citycar.Models;

namespace citycar.Controllers
{
    public class ProprietairesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProprietairesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Proprietaires
        public async Task<IActionResult> Index()
        {
            return View(await _context.Proprietaire.ToListAsync());
        }

        // GET: Proprietaires/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            var proprietaire = await _context.Proprietaire
                .Include(x => x.Voitures)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proprietaire == null)
            {
                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            return View(proprietaire);
        }

        // GET: Proprietaires/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proprietaires/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Prenom")] Proprietaire proprietaire)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proprietaire);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proprietaire);
        }

        // GET: Proprietaires/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View();

            }

            var proprietaire = await _context.Proprietaire.FindAsync(id);
            if (proprietaire == null)
            {

                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View(proprietaire);

            }
            return View(proprietaire);
        }

        // POST: Proprietaires/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Prenom")] Proprietaire proprietaire)
        {
            if (id != proprietaire.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proprietaire);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProprietaireExists(proprietaire.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proprietaire);
        }

        // GET: Proprietaires/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proprietaire = await _context.Proprietaire
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proprietaire == null)
            {
                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View(proprietaire);

            }

            return View(proprietaire);
        }

        // POST: Proprietaires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //suppression en cascade !!

            //On va recuperer la list de ses voitures.
            var listVoiture = await _context.Voitures.Where(x => x.Proprietaire.Id == id).ToListAsync();

            //Supprimer les commentaires de ses voitures et les voitures
            if (listVoiture != null)
            {
                foreach (var v in listVoiture)
                {
                    var listCommentaire = await _context.Commentaire.Where(x => x.Voiture.Id == v.Id).ToListAsync();
                    if(listCommentaire != null)
                    {
                        foreach (var c in listCommentaire)
                        {
                            _context.Commentaire.Remove(c);                            
                        }
                        await _context.SaveChangesAsync();
                    }
                    _context.Voitures.Remove(v);

                }

                await _context.SaveChangesAsync();
            }

            //Supprime le proprietaire !
            if (ProprietaireExists(id))
            {
                var proprietaire = await _context.Proprietaire.FindAsync(id);
                _context.Proprietaire.Remove(proprietaire);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }

            else
            {
                ViewData["exceptionProprietaireId"] = " Ce proprietaire n'existe pas";
                return View();
            }


        }

        private bool ProprietaireExists(int id)
        {
            return _context.Proprietaire.Any(e => e.Id == id);
        }
    }
}

citycar/Controllers/VoituresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using citycar.Data;
using citycar.Models;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace citycar.Controllers
{
    public class VoituresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VoituresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Voitures
        public async Task<IActionResult> Index()
        {
            return View(await _context.Voitures.Include(x => x.Proprietaire).Include(x => x.Categorie).ToListAsync());
        }

        // GET: Voitures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            var voiture = await _context.Voitures
                .Include(x => x.Proprietaire)
                .Include(x => x.Categorie)
                .Include(x => x.Commentaires)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                ViewData["exceptionVoitureId"] = "Cet id " + id + " n'existe pas ";
                return View();
            }

            return View(voiture);
        }

        // GET: Voitures/Create
        public IActionResult Create(int? id)
        {
            Proprietaire proprietaire = null;
            if (id != null)
            {
                 proprietaire = _context.Proprietaire.Where(x => x.Id == id).FirstOrDefault();
                if (proprietaire != null) 
                    ViewData["Proprietaire"] = proprietaire;
            }
            return View();
        }

        // POST: Voitures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Marque,Modele,Cylindree,Prix,Image")] Voiture voiture, Categories categories, Proprietaire proprietaire)
        {
            if (ModelState.IsValid)
            {
                //recupere l'image passer dans le formulaire
                
                if(Request.Form.Files.Count > 0)
                {
                    var file = Request.Form.Files[0];
                    var filePath = @"wwwroot/img/" + file.FileName;
                    using var stream = System.IO.File.Create(filePath);
                    await file.CopyToAsync(stream);
                    voiture.Image = file.FileName;
                }
                
                //Recupere tous les proprietes de la voiture avant l'insertion                
                voiture.Categorie = _context.Categories.FirstOrDefault(x => x.NomCategories == categories.NomCategories);
                if(_context.Proprietaire.Any(x => x.Id == proprietaire.Id))
                {
                    voiture.Proprietaire =  _context.Proprietaire.FirstOrDefault(x => x.Id == proprietaire.Id);

                }
                if(proprietaire.Id == 0)
                {
                     _context.Proprietaire.Add(proprietaire);
                    await _context.SaveChangesAsync();
                    voiture.Proprietaire =  await _context.Proprietaire.OrderByDescending(x => x.Id).FirstAsync();
                }
                // id autoincrement !
                voiture.Id = 0;
                


                _context.Add(voiture);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(voiture);
        }

        // GET: Voitures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            var voiture = await _context.Voitures
                .Include(x => x.Proprietaire)
                .Include(x => x.Categorie)
                .Include(x => x.Commentaires)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de trouver cet Id " + id;
                return View();
            }
            return View(voiture);
        }

        // POST: Voitures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Marque,Modele,Cylindree,Prix,Image")] Voiture voiture, String FisrtNameImage, String CategorieId, String ProprietaireId)
        {
            
            if (id != voiture.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //Si on a un nouveau fichier on supprimer l'ancien du serveur
                if(Request.Form.Files.Count > 0)
                {
                    
                    if(FisrtNameImage != null)
                    {
                        var aFilePath = @"wwwroot/img/" + FisrtNameImage;
                        try
                        {
                            System.IO.File.Delete(aFilePath);
                        }
                        catch (Exception)
                        {

                            throw;
                        }
                    }
                    
                    //recupere l'image passer dans le formulaire
                    var file = Request.Form.Files[0];
                    if (file.Length > 0)
                    {
                        var filePath = @"wwwroot/img/" + file.FileName;
                        using var stream = System.IO.File.Create(filePath);
                        await file.CopyToAsync(stream);
                    }
                    voiture.Image = file.FileName;
                }
                else { voiture.Image = FisrtNameImage; }

                
                //Recupere tous les proprietes de la voiture avant l'insertion                
                voiture.Proprietaire = await _context.Proprietaire.Where(x => x.Id == int.Parse(ProprietaireId)).FirstAsync();
                voiture.Categorie = await _context.Categories.Where(x => x.Id == int.Parse(CategorieId)).FirstAsync();                 



                try
                {
                    _context.Update(voiture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VoitureExists(voiture.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(voiture);
        }

        // GET: Voitures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            var voiture = await _context.Voitures
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de trouver cet Id " + id;
                return View(voiture);

            }

            return View(voiture);
        }

        // POST: Voitures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //suppresion des commentaire de la voiture  
            var listCommentaire = await _context.Commentaire.Where(x => x.Voiture.Id == id).ToListAsync();
            if(listCommentaire != null)
            {
                foreach (var c in listCommentaire)
                {
                    _context.Commentaire.Remove(c);

                }
                await _context.SaveChangesAsync();
            }


            if (VoitureExists(id))
            {
                var voiture = await _context.Voitures.FindAsync(id);
                _context.Voitures.Remove(voiture);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["exceptionVoitureId"] = " Cette voiture n'existe pas";
                return View();
            }



        }

        private bool VoitureExists(int id)
        {
            return _context.Voitures.Any(e => e.Id == id);
        }
    }
}

citycar/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - citycar</title>
    <link rel="icon" type="image/png" sizes="16x16" href="~/img/citycar.png">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&family=Roboto&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body style="background-color: #ececec">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm  border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/img/citycar.png" alt="citycar" width="50" height="40"></a>
                <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between ">
                    <ul class="navbar-nav flex-grow-1 nav-tabs">
                        <li class="nav-item">
                            <a class="nav-link  text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Voitures" asp-action="Index">Voitures</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-light" asp-area="" asp-controller="Proprietaires" asp-action="Index">Proprietaires</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3 my-3 ">
            @RenderBody()
        </main>
    </div>
 
        <footer class="border-top footer text-white text-center" style="background-color: #44566c">
            <div class="container">
                <ul class="list-unstyled list-inline text-center">
                    <li class="list-inline-item">
                        <a class="btn-floating btn-fb mx-1">
                            <i class="fa fa-facebook"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-tw mx-1">
                            <i class="fa fa-twitter"> </i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-li mx-1">
                            <i class="fa fa-whatsapp"></i>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a class="btn-floating btn-dribbble mx-1">
                            <i class="fa fa-instagram"> </i>
                        </a>
                    </li>
                </ul>
                
                &copy; 2021 - citycar -Marie-Christelle-Serge-Xavier-Richard-Kossi
            </div>
        </footer>
      
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
</body>
</html>