citycar/Controllers/CommentairesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using citycar.Data;
using citycar.Models;
using System.Text.RegularExpressions;

namespace citycar.Controllers
{
    public class CommentairesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CommentairesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // POST: Commentaires/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,TextCommentaire,Date")] Commentaire commentaire, Voiture voiture)
        {
            
            commentaire.Voiture = _context.Voitures.FirstOrDefault(m => m.Id == voiture.Id);
            commentaire.Id = 0;
            

            if (ModelState.IsValid)
            {
                _context.Add(commentaire);
                await _context.SaveChangesAsync();
                return RedirectToAction("Details", "Voitures", new { id = voiture.Id });
            }
            return RedirectToAction("Details", "Voitures", new { id = voiture.Id });
        }

        // POST: Commentaires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int CommentaireId, Voiture voiture)
        {
            var commentaire = await _context.Commentaire.FindAsync(CommentaireId);
            _context.Commentaire.Remove(commentaire);
            await _context.SaveChangesAsync();
            return RedirectToAction("Details", "Voitures", new { id = voiture.Id });
        }

        private bool CommentaireExists(int id)
        {
            return _context.Commentaire.Any(e => e.Id == id);
        }
        

    }
}

citycar/Controllers/ProprietairesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using citycar.Data;
using citycar.Models;

namespace citycar.Controllers
{
    public class ProprietairesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public ProprietairesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Proprietaires
        public async Task<IActionResult> Index()
        {
            return View(await _context.Proprietaire.ToListAsync());
        }

        // GET: Proprietaires/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            var proprietaire = await _context.Proprietaire
                .Include(x => x.Voitures)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proprietaire == null)
            {
                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            return View(proprietaire);
        }

        // GET: Proprietaires/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Proprietaires/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nom,Prenom")] Proprietaire proprietaire)
        {
            if (ModelState.IsValid)
            {
                _context.Add(proprietaire);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(proprietaire);
        }

        // GET: Proprietaires/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View();

            }

            var proprietaire = await _context.Proprietaire.FindAsync(id);
            if (proprietaire == null)
            {

                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View(proprietaire);

            }
            return View(proprietaire);
        }

        // POST: Proprietaires/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nom,Prenom")] Proprietaire proprietaire)
        {
            if (id != proprietaire.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(proprietaire);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProprietaireExists(proprietaire.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(proprietaire);
        }

        // GET: Proprietaires/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var proprietaire = await _context.Proprietaire
                .FirstOrDefaultAsync(m => m.Id == id);
            if (proprietaire == null)
            {
                ViewData["exceptionProprietaireId"] = "Impossible de traiter cette demande !!!";
                return View(proprietaire);

            }

            return View(proprietaire);
        }

        // POST: Proprietaires/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //suppression en cascade !!

            //On va recuperer la list de ses voitures.
            var listVoiture = await _context.Voitures.Where(x => x.Proprietaire.Id == id).ToListAsync();

            //Supprimer les commentaires de ses voitures et les voitures
            if (listVoiture != null)
            {
                foreach (var v in listVoiture)
                {
                    var listCommentaire = await _context.Commentaire.Where(x => x.Voiture.Id == v.Id).ToListAsync();
                    if(listCommentaire != null)
                    {
                        foreach (var c in listCommentaire)
                        {
                            _context.Commentaire.Remove(c);                            
                        }
                        await _context.SaveChangesAsync();
                    }
                    _context.Voitures.Remove(v);

                }

                await _context.SaveChangesAsync();
            }

            //Supprime le proprietaire !
            if (ProprietaireExists(id))
            {
                var proprietaire = await _context.Proprietaire.FindAsync(id);
                _context.Proprietaire.Remove(proprietaire);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));

            }

            else
            {
                ViewData["exceptionProprietaireId"] = " Ce proprietaire n'existe pas";
                return View();
            }


        }

        private bool ProprietaireExists(int id)
        {
            return _context.Proprietaire.Any(e => e.Id == id);
        }
    }
}

citycar/Controllers/VoituresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using citycar.Data;
using citycar.Models;
using System.IO;
using Microsoft.AspNetCore.Http;

namespace citycar.Controllers
{
    public class VoituresController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VoituresController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Voitures
        public async Task<IActionResult> Index()
        {
            return View(await _context.Voitures.Include(x => x.Proprietaire).Include(x => x.Categorie).ToListAsync());
        }

        // GET: Voitures/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            var voiture = await _context.Voitures
                .Include(x => x.Proprietaire)
                .Include(x => x.Categorie)
                .Include(x => x.Commentaires)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                ViewData["exceptionVoitureId"] = "Cet id " + id + " n'existe pas ";
                return View();
            }

            return View(voiture);
        }

        // GET: Voitures/Create
        public IActionResult Create(int? id)
        {
            Proprietaire proprietaire = null;
            if (id != null)
            {
                 proprietaire = _context.Proprietaire.Where(x => x.Id == id).FirstOrDefault();
                if (proprietaire != null) 
                    ViewData["Proprietaire"] = proprietaire;
            }
            return View();
        }

        // POST: Voitures/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Marque,Modele,Cylindree,Prix,Image")] Voiture voiture, Categories categories, Proprietaire proprietaire)
        {
            if (ModelState.IsValid)
            {
                //recupere l'image passer dans le formulaire
                
                if(Request.Form.Files.Count > 0)
                {
                    var file = Request.Form.Files[0];
                    var filePath = @"wwwroot/img/" + file.FileName;
                    using var stream = System.IO.File.Create(filePath);
                    await file.CopyToAsync(stream);
                    voiture.Image = file.FileName;
                }
                
                //Recupere tous les proprietes de la voiture avant l'insertion                
                voiture.Categorie = _context.Categories.FirstOrDefault(x => x.NomCategories == categories.NomCategories);
                if(_context.Proprietaire.Any(x => x.Id == proprietaire.Id))
                {
                    voiture.Proprietaire =  _context.Proprietaire.FirstOrDefault(x => x.Id == proprietaire.Id);

                }
                if(proprietaire.Id == 0)
                {
                     _context.Proprietaire.Add(proprietaire);
                    await _context.SaveChangesAsync();
                    voiture.Proprietaire =  await _context.Proprietaire.OrderByDescending(x => x.Id).FirstAsync();
                }
                // id autoincrement !
                voiture.Id = 0;
                


                _context.Add(voiture);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(voiture);
        }

        // GET: Voitures/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            var voiture = await _context.Voitures
                .Include(x => x.Proprietaire)
                .Include(x => x.Categorie)
                .Include(x => x.Commentaires)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de trouver cet Id " + id;
                return View();
            }
            return View(voiture);
        }

        // POST: Voitures/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Marque,Modele,Cylindree,Prix,Image")] Voiture voiture, String FisrtNameImage, String CategorieId, String ProprietaireId)
        {
            
            if (id != voiture.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                //Si on a un nouveau fichier on supprimer l'ancien du serveur
                if(Request.Form.Files.Count > 0)
                {
                    
                    if(FisrtNameImage != null)
                    {
                        var aFilePath = @"wwwroot/img/" + FisrtNameImage;
                        try
                        {
                            System.IO.File.Delete(aFilePath);
                        }
                        catch (Exception)
                        {

                            throw;
                        }
                    }
                    
                    //recupere l'image passer dans le formulaire
                    var file = Request.Form.Files[0];
                    if (file.Length > 0)
                    {
                        var filePath = @"wwwroot/img/" + file.FileName;
                        using var stream = System.IO.File.Create(filePath);
                        await file.CopyToAsync(stream);
                    }
                    voiture.Image = file.FileName;
                }
                else { voiture.Image = FisrtNameImage; }

                
                //Recupere tous les proprietes de la voiture avant l'insertion                
                voiture.Proprietaire = await _context.Proprietaire.Where(x => x.Id == int.Parse(ProprietaireId)).FirstAsync();
                voiture.Categorie = await _context.Categories.Where(x => x.Id == int.Parse(CategorieId)).FirstAsync();                 



                try
                {
                    _context.Update(voiture);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VoitureExists(voiture.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(voiture);
        }

        // GET: Voitures/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de traiter cette demande !!!";
                return View();
            }

            var voiture = await _context.Voitures
                .FirstOrDefaultAsync(m => m.Id == id);
            if (voiture == null)
            {
                ViewData["exceptionVoitureId"] = "Impossible de trouver cet Id " + id;
                return View(voiture);

            }

            return View(voiture);
        }

        // POST: Voitures/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            //suppresion des commentaire de la voiture  
            var listCommentaire = await _context.Commentaire.Where(x => x.Voiture.Id == id).ToListAsync();
            if(listCommentaire != null)
            {
                foreach (var c in listCommentaire)
                {
                    _context.Commentaire.Remove(c);

                }
                await _context.SaveChangesAsync();
            }


            if (VoitureExists(id))
            {
                var voiture = await _context.Voitures.FindAsync(id);
                _context.Voitures.Remove(voiture);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else
            {
                ViewData["exceptionVoitureId"] = " Cette voiture n'existe pas";
                return View();
            }



        }

        private bool VoitureExists(int id)
        {
            return _context.Voitures.Any(e => e.Id == id);
        }
    }
}

citycar/Views/Voitures/Create.cshtml
@model citycar.Models.Voiture

@{
    ViewData["Title"] = "Create";
    Proprietaire proprietaire = ViewData["Proprietaire"] as Proprietaire;
}
<script src="~/js/image.js"></script>
<h1>Create</h1>

<h4>Voiture</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data" name="form">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Marque" class="control-label"></label>
                <input asp-for="Marque" class="form-control"  required/>
                <span asp-validation-for="Marque" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Modele" class="control-label"></label>
                <input asp-for="Modele" class="form-control" required/>
                <span asp-validation-for="Modele" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cylindree" class="control-label"></label>
                <input asp-for="Cylindree" class="form-control" min="0" required/>
                <span asp-validation-for="Cylindree" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prix" class="control-label"></label>
                <input asp-for="Prix" class="form-control" name="prix" min="0" required/>
                <span asp-validation-for="Prix" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Image" class="control-label"></label>
                <input asp-for="Image" type="file" class="form-control" name="file" />
                <span asp-validation-for="Image" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label for="Categorie-select" class="control-label">Catégorie :</label>
                <select name="NomCategories" id="Categorie-select" class="form-control" required>
                    <option value="">--Veuillez choisir une option--</option>
                    <option value="Berline">Berline</option>
                    <option value="SUV">SUV</option>
                    <option value="Roadster">Roadster</option>
                    <option value="Cabriolet">Cabriolet</option>
                    <option value="Familiale">Familiale</option>
                    <option value="Coupé">Coupé</option>
                    <option value="Pickup">Pickup</option>
                    <option value="voiture sportive">voiture sportive</option>
                    <option value="4×4">4×4</option>
                </select>
            </div>
            @if (proprietaire != null)
            {
                <div class="form-group">
                    <input type="hidden" name="Id" class="form-control" id="Nom" value="@proprietaire.Id" />
                </div>
                <div class="form-group">
                    <input type="hidden" name="Nom" class="form-control" id="Nom" value="@proprietaire.Nom" />
                </div>
                <div class="form-group">
                    <input type="hidden" name="Prenom" class="form-control" id="Prenom" value="@proprietaire.NomComplet" />
                </div>
            }
            else
            {
                <div class="form-group">
                    <label for="Nom" class="control-label">Nom propriétaire</label>
                    <input name="Nom" class="form-control" id="Nom" required/>
                </div>
                <div class="form-group">
                    <label for="Prenom" class="control-label">Prenom propriétaire</label>
                    <input name="Prenom" class="form-control" id="Prenom" required/>
                </div>
            }

            <div class="form-group">
                <input type="submit" onclick="return validate();" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

citycar/Views/Voitures/Delete.cshtml
@model citycar.Models.Voiture

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Voiture</h4>
    <hr />
    @{
        if (Model != null)
        {

            <dl class="row">
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Marque)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Marque)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Modele)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Modele)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Cylindree)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Cylindree)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Prix)
                </dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Prix)
                </dd>
                <dt class="col-sm-2">
                    @Html.DisplayNameFor(model => model.Image)
                </dt>
                <dd class="col-sm-10">
                    <img src="~/img/@Model.Image" alt="@Model.Modele" class="img-thumbnail" style="max-width:100px; max-height:100px" title="@Model.Marque - @Model.Modele" />
                </dd>
            </dl>

            <form asp-action="Delete">
                <input type="hidden" asp-for="Id" />
                <input type="submit" value="Delete" class="btn btn-danger" /> |
                <a asp-action="Index">Back to List</a>
            </form>
        }
        else
        {
            if ((ViewData["exceptionVoitureId"]) != null)
            {
                <p style="color:red">@ViewData["exceptionVoitureId"]  </p>

            }
        }
    }
</div>

citycar/Views/Voitures/Details.cshtml
@model citycar.Models.Voiture
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
<script src="~/ckeditor/ckeditor.js"></script>
<link href="~/ckeditor/contents.css" rel="stylesheet" />
@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>


<div>
    <h4>Voiture</h4>

    @{
        if (Model != null)
        {
            <table class="table">
                <tr>
                    <td>
                        <img src="~/img/@Model.Image" alt="@Model.Image" class="img-thumbnail w-75 h-auto" />
                        <dl class="row">
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Marque)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Marque)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Modele)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Modele)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Cylindree)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Cylindree)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Prix)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Prix)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Categorie)
                            </dt>
                            <dd class="col-sm-10">
                                @Html.DisplayFor(model => model.Categorie.NomCategories)
                            </dd>
                            <dt class="col-sm-2">
                                @Html.DisplayNameFor(model => model.Proprietaire)
                            </dt>
                            <dd class="col-sm-10">
                                <a asp-controller="Proprietaires" asp-action="Details" asp-route-id="@Model.Proprietaire.Id">@Model.Proprietaire.NomComplet</a>
                            </dd>
                        </dl>
                    </td>


                    @*Ajouter commentaire*@
                <td class="w-100 h-auto" style="display:flex;flex-direction: column">
                    @foreach (var c in Model.Commentaires)
                    {
                    <form asp-controller="Commentaires" asp-action="Delete">
                        <span>@c.Date : @Html.Raw(c.TextCommentaire) </span>
                        <input type="hidden" name="CommentaireId" value="@c.Id" />
                        <input type="hidden" name="Id" value="@Model.Id" />
                        <input type="hidden" name="Marque" value="@Model.Marque" />
                        <input type="hidden" name="Modele" value="@Model.Modele" />
                        <input type="submit" value="supprimer" />
                    </form>
                    }
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <form asp-controller="Commentaires" asp-action="Create">
                            <textarea id="editor" name="TextCommentaire" rows="5" cols="50"></textarea>
                            <script>
                                CKEDITOR.replace(
                                    'editor');
                            </script>

                            <input type="hidden" name="Date" value="@DateTime.Now" />
                            <input type="hidden" name="Id" value="@Model.Id" />
                            <input type="hidden" name="Marque" value="@Model.Marque" />
                            <input type="hidden" name="Modele" value="@Model.Modele" />
                            <input style="margin-top:1em" type="submit" class="btn btn-primary" value="Ajouter un commentaire" />
                        </form>

                    }
                    </td>
                </tr>
            </table>

        }
        else
        {
            if ((ViewData["exceptionVoitureId"]) != null)
            {
                <p style="color:red">@ViewData["exceptionVoitureId"]  </p>

            }
        }
    }
    <hr />

</div>
<div>
    @if (SignInManager.IsSignedIn(User))
    {
        if (Model != null)
        {
            <a asp-action="Edit" asp-route-id="@Model.Id">Edit |</a>
        }

    }
    <a asp-action="Index">Back to List</a>
</div>

citycar/Views/Voitures/Index.cshtml
@model IEnumerable<citycar.Models.Voiture>
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

@{
    ViewData["Title"] = "Index";
}

<h1>Voitures</h1>
<p>
    @if (SignInManager.IsSignedIn(User))
    {
        <a asp-action="Create">Create New</a>
    }
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Marque)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Modele)
            </th>
            <th>
                Catégorie
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cylindree)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Prix)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Image)
            </th>
            <th>
                Propriétaire
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Marque)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Modele)
                </td>
                <td>
                    @item.Categorie.NomCategories
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cylindree)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Prix) 
                </td>
                <td>
                    <img src="~/img/@item.Image" alt="@item.Modele" class="img-thumbnail" style="max-width:100px; max-height:100px" title="@item.Marque - @item.Modele"/>
                </td>
                <td>
                    <a asp-controller="Proprietaires" asp-action="Details" asp-route-id="@item.Proprietaire.Id">@item.Proprietaire.NomComplet</a>
                </td>
                <td>
                    @if (SignInManager.IsSignedIn(User))
                    {
                        <a asp-action="Edit" asp-route-id="@item.Id">Edit |</a>
                        <a asp-action="Details" asp-route-id="@item.Id">Details |</a>
                        <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                    }
                    else
                    {
                        <a asp-action="Details" asp-route-id="@item.Id">Details </a>
                    }

                </td>
            </tr>
        }
    </tbody>

    <th></th>
</table>